workflow:
  rules:

    # If the branch is empty do not run the pipeline
    - if: $CI_COMMIT_BRANCH
      changes:
        compare_to: 'refs/heads/main'
        paths:
          - '*'
    # When opening a merge request run the pipeline
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # If a merge request has been opened for the branch do not run the branch pipeline
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # When committing run the pipeline
    - if: $CI_COMMIT_BRANCH

services:
  - postgres:latest

variables:
  POSTGRES_DB: ToothTrekLogsTest
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: test
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - build
  - test

# Flutter
build-frontend:
  image: "ghcr.io/cirruslabs/flutter:3.13.9"
  stage: build

  script:
    - cd Website/Frontend
    - flutter pub get
    - flutter build web 
  tags:
    - docker
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $CI_PROJECT_DIR/Website/Frontend/.dart_tool/
      - $CI_PROJECT_DIR/Website/Frontend/build/web/

test-frontend:
  stage: test
  needs: ["build-frontend"]

  image: "ghcr.io/cirruslabs/flutter:3.13.9"
  tags:
    - docker

  script:
    - cd Website/Frontend
    - flutter test

# Express
build-backend:
  stage: build

  image: node:18
  tags:
    - docker

  script:
    - cd Website/Backend
    - npm install

test-backend:
  stage: test
  needs: ["build-backend"]

  image: node:18
  tags:
    - docker

  script:
    - cd Website/Backend
    - npm test 

  # Allow failure til we have tests
  allow_failure: true

# Java Middleware

# !!! Add one per service !!!

# Template
build-template-middleware:
  stage: build

  image: maven:3.9.5-eclipse-temurin-21-alpine
  tags:
    - docker

  script:
    - cd Middleware/template
    - mvn --show-version install -DskipTests

test-template-middleware:
  stage: test
  needs: ["build-template-middleware"]

  image: maven:3.9.5-eclipse-temurin-21-alpine
  tags:
    - docker

  script:
    - cd Middleware/template
    - mvn --show-version test
  retry: 2

# Logs
build-logs-middleware:
  stage: build

  image: maven:3.9.5-eclipse-temurin-21-alpine
  tags:
    - docker

  script:
    - cd Middleware/Logs
    - mvn --show-version install -DskipTests

test-logs-middleware:
  stage: test
  needs: ["build-logs-middleware"]

  image: maven:3.9.5-eclipse-temurin-21-alpine
  tags:
    - docker

  script:
    - cd Middleware/Logs
    - mvn --show-version test