{
 "title": "Toothtrek",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests in the last hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(total_requests[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Log-ins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "total_requests{Entity=\"patients\", method=\"post\", statusCode=\"200\"}",
     "legendFormat": "Number of logged in users"
    }
   ]
  },
  {
   "title": "HTTP status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (changes(total_requests{statusCode=\"200\"}[1m]))",
     "legendFormat": "http 200"
    },
    {
     "expr": "sum by(type) (rate(total_requests{statusCode=\"500\"}[5m])) * 300",
     "legendFormat": "http 500"
    }
   ]
  }
 ]
}