global:
  scrape_interval: 5s 
  evaluation_interval: 5s 

scrape_configs: 
  - job_name: 'toothtrek_website_backend'
    metrics_path: '/metrics' 
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:3001']
